#!/bin/bash

# Script to prepare wolfSSL for Debian packaging
# This ensures all necessary files are in place before building

set -e

echo "Preparing wolfSSL for Debian packaging..."

# Ensure we're in the right directory
if [ ! -f "debian/control.in" ]; then
    echo "Error: debian/control.in not found. Please run this script from the wolfSSL source root."
    exit 1
fi

# Generate debian/control from debian/control.in if it doesn't exist
if [ ! -f "debian/control" ]; then
    echo "Generating debian/control from debian/control.in..."
    cp debian/control.in debian/control
fi

# Ensure rules file is executable
chmod +x debian/rules

# Only generate configure script if we're going to build, not just for source packages
if [ "$1" != "--source-only" ] && [ ! -f "configure" ]; then
    echo "Generating configure script..."
    if [ -f "autogen.sh" ]; then
        ./autogen.sh
    else
        echo "Warning: No configure script and no autogen.sh found"
    fi
fi

# Ensure proper permissions on other scripts
if [ -f "debian/create-orig-tarball.sh" ]; then
    chmod +x debian/create-orig-tarball.sh
fi

if [ -f "debian/create-source-package.sh" ]; then
    chmod +x debian/create-source-package.sh
fi

if [ -f "debian/test-build.sh" ]; then
    chmod +x debian/test-build.sh
fi

# Clean any existing build artifacts that might interfere with packaging
echo "Cleaning build artifacts..."
find . -name "*.o" -delete 2>/dev/null || true
find . -name "*.lo" -delete 2>/dev/null || true
find . -name "*.la" -delete 2>/dev/null || true
find . -name "*.so" -delete 2>/dev/null || true
find . -name "*.so.*" -delete 2>/dev/null || true
rm -rf .libs src/.libs wolfcrypt/src/.libs 2>/dev/null || true
rm -rf wrapper/Ada/obj wrapper/Ada/lib 2>/dev/null || true
rm -f config.log config.status libtool stamp-h stamp-h1 .build_params 2>/dev/null || true
rm -f Makefile src/Makefile wolfcrypt/Makefile wolfcrypt/src/Makefile 2>/dev/null || true
find . -name "*.stdout" -delete 2>/dev/null || true
find . -name "*.stderr" -delete 2>/dev/null || true
find . -name "*~" -delete 2>/dev/null || true
find . -name ".deps" -type d -exec rm -rf {} + 2>/dev/null || true
find . -name ".dirstamp" -delete 2>/dev/null || true
rm -f out*.log test.log 2>/dev/null || true
# Remove binary test files and artifacts that cause dpkg-source issues
rm -f certeccrsa.der 2>/dev/null || true
rm -f tests/bio_write_test.txt 2>/dev/null || true
rm -f tests/*.tmp 2>/dev/null || true
rm -f wolfcrypt/benchmark/*.info 2>/dev/null || true
rm -f wolfssl-*.tar.gz 2>/dev/null || true
rm -f aminclude.am 2>/dev/null || true
# Remove coverage files
find . -name "*.gcda" -delete 2>/dev/null || true
find . -name "*.gcno" -delete 2>/dev/null || true
find . -name "*.gcov" -delete 2>/dev/null || true
find . -name "*.profdata" -delete 2>/dev/null || true
# Remove autogenerated files that can cause upstream sync issues
rm -f build-aux/ltmain.sh 2>/dev/null || true
rm -f m4/libtool.m4 m4/ltoptions.m4 m4/ltsugar.m4 m4/ltversion.m4 m4/lt~obsolete.m4 2>/dev/null || true
rm -f aclocal.m4 2>/dev/null || true
rm -f support/wolfssl.pc wolfssl-config wolfssl/options.h config.in 2>/dev/null || true
rm -f wolfcrypt/src/fips_test.c wolfcrypt/src/wolfcrypt_first.c wolfcrypt/src/wolfcrypt_last.c 2>/dev/null || true
rm -f wolfcrypt/test/test_paths.h rpm/spec 2>/dev/null || true
rm -f certeccrsa.pem ecc-key.pem test-write-dhparams.pem 2>/dev/null || true

echo "Build preparation completed successfully!"

if [ "$1" = "--source-only" ]; then
    echo "Source package preparation mode - skipped configure generation"
else
    echo ""
    echo "You can now:"
    echo "1. Create upstream tarball: ./debian/create-orig-tarball.sh"
    echo "2. Build source package: dpkg-buildpackage -S -us -uc"
    echo "3. Build binary packages: dpkg-buildpackage -b -us -uc"
    echo "4. Or run tests: ./debian/test-build.sh"
fi
